### ISSUE TITLE
Adding "key-" to API key causing error

### ISSUE THREAD

**Issue by florianweich** [twof/VaporMailgunService#11]
You are adding the prefix **"key-"** to the API key if it's not present. See:
https://github.com/twof/VaporMailgunService/blob/d10e245141a034d6b74955ae67d8a80f7929e38d/Sources/Mailgun/Mailgun.swift#L90

The problem is that my Mailgun API key does in fact **not** contain a "key-" prefix. So when it gets added I receive an authentication error (as expected).

I would suggest removing this check since there seem to be keys without the prefix.

**Comment by florianweich** [comment]
I created a pull request for this: https://github.com/twof/VaporMailgunService/pull/12

**Comment by foscomputerservices** [comment]
I came here to write this very same thing!  Mailgun's documentation does seem to be inconsistent on the matter.  In the [Authentication](https://documentation.mailgun.com/en/latest/api-intro.html#authentication) section they very clearly add 'key-' to the key.  However, in the [Message Examples](https://documentation.mailgun.com/en/latest/api-sending.html#examples) section they omit it.

I have been banging my head on this for the past day with 401 errors and just concluded the same as @florianweich; 'key-' must be omitted.

**Comment by twof** [comment]
That's really interesting. It was added initially because folks were having the opposite problem where they were leaving `key-` off and it was 401'ing.

Do your private api keys start with `key-`?

<img width="339" alt="screen shot 2018-05-31 at 10 44 54 am" src="https://user-images.githubusercontent.com/5561501/40798557-2b4b09a8-64c0-11e8-8631-d6e6afd67d6c.png">

**Comment by foscomputerservices** [comment]
@twof, my Private key does not start with 'key-'.  My Public key starts with 'pubkey-'.

**Comment by twof** [comment]
Very strange. I wonder if that's a recent change. Thanks for the report! If you `vapor update` you should be good to go :)
