### ISSUE TITLE
'Reply To' field missing

### ISSUE THREAD

**Issue by peterstojanowski** [twof/VaporMailgunService#16]
Hi Alex,
any chance to extend functionality for the _reply to_ field?
Thanks

**Comment by MihaelIsaev** [comment]
I've just checked mailgun API reference and it's possible using custom MIME header
<img width="918" alt="2018-09-12 14 50 49" src="https://user-images.githubusercontent.com/1272610/45423226-56f6c880-b69b-11e8-8894-d876371282dc.png">
So looks like it's not hard to implement that 🙂

**Comment by twof** [comment]
Thanks for the report :)

**Comment by twof** [comment]
Merged and resolved 👍
