### ISSUE TITLE
SecTaskLoadEntitlements failed error=22 • No email sent

### ISSUE THREAD

**Issue by rbeckACQ** [twof/VaporMailgunService#27]
I'm trying a very basic email send, and I can't seem to get mailgun to work:

````
let emailmessage = Mailgun.Message(
                from: "noreply@digital-possibilities.com",
                to: email,
                subject: "Your Request to Change password.",
                text: "Here is your accesskey: \(cpRequest.accessKey)",
                html: "<b>Here is your accesskey: <u>\(cpRequest.accessKey)</u></b>"
            )
            
            let mailgun = try req.make(Mailgun.self)
            let sendmessage = try mailgun.send(emailmessage, on: req)
````

In the console I see: 

```
2019-03-07 07:54:03.298354-0500 Run[63330:1820318] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=63330
2019-03-07 07:54:03.298472-0500 Run[63330:1820318] SecTaskCopyDebugDescription: Run[63330]/0#-1 LF=0
2019-03-07 07:56:03.233181-0500 Run[63330:1820324] Received XPC error Connection interrupted for message type 3 kCFNetworkAgentXPCMessageTypePACQuery
2019-03-07 07:56:03.233348-0500 Run[63330:1820324] Received XPC error Connection invalid for message type 3 kCFNetworkAgentXPCMessageTypePACQuery

```
and no email is sent.

Console is set up as:

```
    // MailGun
    let mailgun = Mailgun(apiKey: "API KEY", domain: "DOMAIN")
    services.register(mailgun, as: Mailgun.self)
```
Where API KEY and DOMAIN are replaced by the info from MailGun

Any idea on what's going wrong?

Using the API KEY and DOMAIN, I've been able to send an email via CURL.

Thanks for your help

**Comment by twof** [comment]
@rbeckACQ Did this ever get resolved? Is the error consistent? Is this from macOS or Linux?

**Comment by rbeckACQ** [comment]
Hi,

No, it never was resolved - I moved to Sengrid.

The issue was discovered on MacOS.

Thanks,

Richard

On Mar 25, 2019, at 6:17 PM, Alex Reilly <notifications@github.com<mailto:notifications@github.com>> wrote:


@rbeckACQ<https://github.com/rbeckACQ> Did this ever get resolved? Is the error consistent? Is this from macOS or Linux?

**Comment by twof** [comment]
ahhh bummer. Looks like your issue is a general macOS issue and unrelated to this library.

https://discussions.apple.com/thread/7359797

Closing this issue given that's the case.

**Comment by lukeify** [comment]
Also receiving this issue. How are we sure this is macOS related?
